// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJFGqy2u5Qysx4eDW03PuLCjrpEkiwogY',
    appId: '1:758440683925:android:8b689974af2ea6bf6cae9c',
    messagingSenderId: '758440683925',
    projectId: 'khoj-9e679',
    databaseURL: 'https://khoj-9e679-default-rtdb.firebaseio.com',
    storageBucket: 'khoj-9e679.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYjkdIj4Motgewy9vnqLb2ZKixjAg8wX8',
    appId: '1:758440683925:ios:a4e5997dfd5e8cf46cae9c',
    messagingSenderId: '758440683925',
    projectId: 'khoj-9e679',
    databaseURL: 'https://khoj-9e679-default-rtdb.firebaseio.com',
    storageBucket: 'khoj-9e679.firebasestorage.app',
    iosBundleId: 'com.example.lostAndFoundFlutter',
  );

}